oooooooooooo .              .                                  .   oooooooooooo
ooooooooooo          |||||||| |||||   ||||  |||||  |||||   .        ooooooooooo
oooooooooo        .     ||    ||  || ||  || ||  || ||                oooooooooo
ooooooooo               ||    |||||  |||||| ||  || ||||         .     ooooooooo
oooooooo                ||    || ||  ||  || ||  || ||                  oooooooo
ooooooo   .             ||    ||  || ||  || |||||  |||||     .          ooooooo
oooooo        .                                                     .    oooooo
ooooo                    ||    ||  ||||  |||||   ||||    2                ooooo
oooo                     ||    || ||  || ||  || ||       0      .          oooo
ooo   .              .   || || || |||||| |||||   ||||    0          .       ooo
oo                       || || || ||  || || ||      ||   2  V  2             oo
o                         ||  ||  ||  || ||  || |||||         .               o
oo             .               .                        .                .   oo
ooo                                        .                                ooo
oooo  .            .                                 .              .      oooo
ooooo                Distributed by Epic Interactive Strategy             ooooo
oooooo    .            Created by Gary and Mary Ann Martin         .     oooooo
ooooooo         .                                    .                  ooooooo
oooooooo                     http://www.eisonline.com     *            oooooooo
ooooooooo   .                                    .                    ooooooooo
oooooooooo               *           .                       .       oooooooooo
ooooooooooo      .                            .                  .  ooooooooooo
oooooooooooo                 .                         .           oooooooooooo

